In [1]:
import numpy as np

In [2]:
#1
a = np.random.random((10,3))
print(a)
print([x[np.abs(x-0.5).argmin()] for x in a])

[[0.70850941 0.96286801 0.73980501]
 [0.36638254 0.18765977 0.25215584]
 [0.87808901 0.42346646 0.02848579]
 [0.34777114 0.21852635 0.97518234]
 [0.08911224 0.57541762 0.67308799]
 [0.30016027 0.09804354 0.09883813]
 [0.11267099 0.91388606 0.89690927]
 [0.31325994 0.62747143 0.68723171]
 [0.12078098 0.53423244 0.32367184]
 [0.87452403 0.7778073  0.15795372]]
[0.7085094130209595, 0.36638253695431855, 0.42346646195630055, 0.3477711387994993, 0.5754176249506447, 0.3001602669315395, 0.11267099265615599, 0.6274714312641224, 0.5342324405211832, 0.7778073005875321]


In [3]:
#2
a=np.random.random((6,6))
print(np.sum(a,axis=1) / np.min(a,axis=0))

[   8.81304457   11.20577614 2372.2177806    36.26504392   33.22207903
   27.84980281]


In [4]:
#3
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
mask = x == 0
x[1:][mask[:-1]].max()

5

In [5]:
#4
x = np.ones(10)
i = np.array([0,1,2,3,5,5,5,8])
print(x + np.bincount(i,minlength=10))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
